# Generated by Django 2.2.17 on 2020-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='newValue',
            field=models.TextField(blank=True),
        ),
    ]
